version: '3'

volumes:
  postgres-data: {}

services:
  db:
    container_name: postgres
    image: postgres
    env_file:
      - config.env
    volumes:
       - postgres-data:/var/lib/postgresql/data
  web:
    container_name: web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./locksmith:/locksmith
    ports:
      - "3000:3000"
    depends_on:
      - db